### ISSUE TITLE
0.13.1 breaks on werkzeug 3: Response' object has no attribute 'charset

### ISSUE THREAD

**Issue by ddorian** [pallets-eco/flask-debugtoolbar#214]
Looks like Response.charset has been deprecated since [2.30](https://github.com/pallets/werkzeug/blob/main/CHANGES.rst#version-230) and was removed in 3:

```python
Traceback (most recent call last):
  File "/home/myproject/.venv/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myproject/.venv/lib/python3.11/site-packages/whitenoise/base.py", line 81, in __call__
    return self.application(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myproject/.venv/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myproject/.venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myproject/.venv/lib/python3.11/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myproject/.venv/lib/python3.11/site-packages/flask/app.py", line 1508, in finalize_request
    response = self.process_response(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myproject/.venv/lib/python3.11/site-packages/flask/app.py", line 2002, in process_response
    response = self.ensure_sync(func)(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myproject/.venv/lib/python3.11/site-packages/flask_debugtoolbar/__init__.py", line 260, in process_response
    content = content.encode(response.charset)
                             ^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'charset'
```

**Comment by ddorian** [comment]
Will be fixed by https://github.com/pallets-eco/flask-debugtoolbar/pull/211
